#!/bin/sh

set -e

echo "🏗️  Building Jekyll site..."
bundle exec jekyll build

echo "🔍 Running HTMLProofer..."
bundle exec htmlproofer ./_site \
  --check-html \
  --check-sri \
  --typhoeus-config='{"headers":{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"}}' \
  --url-ignore "another-page/"

echo "🔎 Running RuboCop..."
bundle exec rubocop -D --config .rubocop.yml

echo "📦 Building gem..."
gem build jekyll-theme-zapocalypse.gemspec
