name: Test Theme

on:
  push:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
            cd /home/runner/work/zapocalypse-theme/zapocalypse-theme/example-site
            bundle install
            cd ..
      - name: build
        run: |
          ls /home/runner/work/zapocalypse-theme/zapocalypse-theme
          script/bootstrap
      - name: test
        run: script/cibuild

  validate_html:
    name: W3C Validate HTML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Check if example-site/ changed
      id: changes
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^example-site/' > /dev/null; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        echo $GITHUB_OUTPUT
      
    - name: Set up Ruby
      if: steps.changes.outputs.changed == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
      
    - name: Install dependencies
      if: steps.changes.outputs.changed == 'true'
      run: bundle install
      
    - name: Run validate-html
      if: steps.changes.outputs.changed == 'true'
      run: bundle exec script/validate-html
