name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # You can change this to match your `.ruby-version` or preferred Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build --source example-site --destination _site
          touch _site/.nojekyll  # ensures _site has a file and avoids glob failure

      - name: Check directory
        run: ls /home/runner/work/zapocalypse-theme/zapocalypse-theme/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          disable_nojekyll: true
